In [2]:
# Verwendete Bibliotheken
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup
import time
import difflib
import statsmodels.api as sm
import statsmodels.formula.api as smf
import random
import numpy as np
from itertools import combinations
import math
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Liste der CSV-Dateipfade
file_paths = [
    r"C:\Users\charb\Downloads\champions-league-2017-CentralEuropeanStandardTime.csv",
    r"C:\Users\charb\Downloads\champions-league-2018-WEuropeStandardTime.csv",
    r"C:\Users\charb\Downloads\champions-league-2020-UTC.csv",
    r"C:\Users\charb\Downloads\champions-league-2021-UTC.csv",
    r"C:\Users\charb\Downloads\champions-league-2022-UTC.csv",
    r"C:\Users\charb\Downloads\champions-league-2023-UTC.csv"
]

In [4]:
# Alle CSV-Dateien einlesen und in einer Liste speichern
dfs = [pd.read_csv(fp) for fp in file_paths]

# Zusammenfügen zu einem DataFrame
combined_df = pd.concat(dfs, ignore_index=True)

In [5]:
combined_df

,Match Number,Round Number,Date,Location,Home Team,Away Team,Group,Result
0,1,1,12/09/2017 20:45,"Estádio da Luz, Lisbon",Benfica,CSKA Moscow,Group A,1 - 2
1,2,1,12/09/2017 20:45,"Old Trafford, Manchester",Manchester United,Basel,Group A,3 - 0
2,13,1,12/09/2017 20:45,"Allianz Arena, Munich",Bayern Munich,Anderlecht,Group B,3 - 0
3,14,1,12/09/2017 20:45,"Celtic Park, Glasgow",Celtic,Paris Saint-Germain,Group B,0 - 5
4,25,1,12/09/2017 20:45,"Stamford Bridge, London",Chelsea,Qarabag,Group C,6 - 0
...,...,...,...,...,...,...,...,...
745,121,SF Game 1,30/04/2024 19:00,Fußball Arena München,Bayern,Real Madrid,NaN,2 - 2
746,122,SF Game 1,01/05/2024 19:00,BVB Stadion Dortmund,Dortmund,Paris,NaN,1 - 0
747,123,SF Game 2,07/05/2024 19:00,Parc des Princes,Paris,Dortmund,NaN,0 - 1
748,124,SF Game 2,08/05/2024 19:00,Estadio Santiago Bernabéu,Real Madrid,Bayern,NaN,2 - 1
749,125,Final,01/06/2024 19:00,Wembley Stadium,Dortmund,Real Madrid,NaN,0 - 2

In [6]:
# Funktion zur Aufteilung des Spielergebnisses in Heim- und Auswärtstore
def split_result(result):
    try:
        home, away = result.strip().split('-')
        return int(home.strip()), int(away.strip())
    except:
        return None, None

# Ergebnis-Spalte anwenden und in zwei neue Spalten aufteilen
combined_df[['Home Goals', 'Away Goals']] = combined_df['Result'].apply(
    lambda x: pd.Series(split_result(x))
)

In [7]:
combined_df

,Match Number,Round Number,Date,Location,Home Team,Away Team,Group,Result,Home Goals,Away Goals
0,1,1,12/09/2017 20:45,"Estádio da Luz, Lisbon",Benfica,CSKA Moscow,Group A,1 - 2,1,2
1,2,1,12/09/2017 20:45,"Old Trafford, Manchester",Manchester United,Basel,Group A,3 - 0,3,0
2,13,1,12/09/2017 20:45,"Allianz Arena, Munich",Bayern Munich,Anderlecht,Group B,3 - 0,3,0
3,14,1,12/09/2017 20:45,"Celtic Park, Glasgow",Celtic,Paris Saint-Germain,Group B,0 - 5,0,5
4,25,1,12/09/2017 20:45,"Stamford Bridge, London",Chelsea,Qarabag,Group C,6 - 0,6,0
...,...,...,...,...,...,...,...,...,...,...
745,121,SF Game 1,30/04/2024 19:00,Fußball Arena München,Bayern,Real Madrid,NaN,2 - 2,2,2
746,122,SF Game 1,01/05/2024 19:00,BVB Stadion Dortmund,Dortmund,Paris,NaN,1 - 0,1,0
747,123,SF Game 2,07/05/2024 19:00,Parc des Princes,Paris,Dortmund,NaN,0 - 1,0,1
748,124,SF Game 2,08/05/2024 19:00,Estadio Santiago Bernabéu,Real Madrid,Bayern,NaN,2 - 1,2,1
749,125,Final,01/06/2024 19:00,Wembley Stadium,Dortmund,Real Madrid,NaN,0 - 2,0,2

In [8]:
# ############################################## 2017-18 ##############################################

# # 1. Champions-League-Spiele laden
# df = pd.read_csv("champions-league-2017-CentralEuropeanStandardTime.csv")
# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
# df_sorted = df.sort_values(by="Date")

# # 2. Früheste Spiele je Runde extrahieren
# first_dates_per_round = (
#     df_sorted.groupby("Round Number")["Date"]
#     .min()
#     .drop_duplicates()
#     .sort_values()
# )
# date_list_for_urls = first_dates_per_round.dt.strftime("%Y-%m-%d").tolist()

# # 3. Tabellen von clubelo.com scrapen
# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
# ucl_rankings = {}

# for date in date_list_for_urls:
#     url = f"http://clubelo.com/{date}/UCL/Ranking"
#     print(f"Scraping: {url}")
    
#     try:
#         response = requests.get(url, headers=headers)
#         soup = BeautifulSoup(response.text, "html.parser")
#         table = soup.find("table", class_="ranking")
        
#         if table:
#             df_table = pd.read_html(str(table))[0]
#             df_table["Date"] = date
#             ucl_rankings[date] = df_table
#         else:
#             print(f"Tabelle nicht gefunden für {date}")
#             ucl_rankings[date] = None
#     except Exception as e:
#         print(f"Fehler bei {date}: {e}")
#         ucl_rankings[date] = None
    
#     time.sleep(5)

# # 4. Alle gescrapten Tabellen kombinieren
# all_tables = [df for df in ucl_rankings.values() if df is not None]
# df_combined = pd.concat(all_tables, ignore_index=True)
# df_combined.to_csv("ucl_elo_rankings_2017_2018.csv", index=False)
# print("Fertig! Tabellen gespeichert in 'ucl_elo_rankings_2017_2018.csv'")

In [9]:
df_2017_18 = pd.read_csv("ucl_elo_rankings_2017_2018.csv")

In [10]:
df_2017_18.head(50)

,Rank,Club,Elo,Unnamed: 3,Last Match,Coach,Date
0,1,1 Real Madrid,2072,NaN,2017-09-09,Zinédine Zidane (since 2016-01-05),2017-09-12
1,2,2 Barcelona,2033,NaN,2017-09-09,Ernesto Valverde (since 2017-07-01),2017-09-12
2,3,3 Bayern,1974,NaN,2017-09-09,Carlo Ancelotti (since 2016-07-01),2017-09-12
3,4,4 Juventus,1954,NaN,2017-09-09,Massimiliano Allegri (since 2014-07-16),2017-09-12
4,5,5 Atlético,1951,NaN,2017-09-09,Diego Simeone (since 2011-12-23),2017-09-12
5,6,6 Chelsea,1919,NaN,2017-09-09,Antonio Conte (since 2016-07-01),2017-09-12
6,7,7 Tottenham,1893,NaN,2017-09-09,Mauricio Pochettino (since 2014-07-01),2017-09-12
7,8,8 Paris SG,1889,NaN,2017-09-08,Unai Emery (since 2016-07-01),2017-09-12
8,9,9 Man City,1889,NaN,2017-09-09,Pep Guardiola (since 2016-07-01),2017-09-12
9,10,10 Napoli,1889,NaN,2017-09-10,Maurizio Sarri (since 2015-06-11),2017-09-12
10,11,11 Man United,1879,NaN,2017-09-09,José Mourinho (since 2016-07-01),2017-09-12
11,12,12 Monaco,1860,NaN,2017-09-09,Leonardo Jardim (since 2014-07-01),2017-09-12
12,13,13 Dortmund,1859,NaN,2017-09-09,Peter Bosz (since 2017-07-01),2017-09-12
13,14,14 Liverpool,1852,NaN,2017-09-09,Jürgen Klopp (since 2015-10-08),2017-09-12
14,15,16 Roma,1832,NaN,2017-08-26,Eusebio Di Francesco (since 2017-06-13),2017-09-12
15,16,17 Sevilla,1829,NaN,2017-09-09,Eduardo Berizzo (since 2017-07-01),2017-09-12
16,17,20 Benfica,1797,NaN,2017-09-08,Rui Vitória (since 2015-07-01),2017-09-12
17,18,22 Шахтар,1773,NaN,2017-09-09,Paulo Fonseca (since 2016-07-01),2017-09-12
18,19,25 Porto,1754,NaN,2017-09-09,Sérgio Conceição (since 2017-07-01),2017-09-12
19,20,30 ЦСКА,1723,NaN,2017-09-08,Viktor Goncharenko (since 2016-12-12),2017-09-12
20,21,31 RB Leipzig,1721,NaN,2017-09-08,Ralph Hasenhüttl (since 2016-07-01),2017-09-12
21,22,32 Sporting,1720,NaN,2017-09-08,Jorge Jesus (since 2015-07-01),2017-09-12
22,23,43 Beşiktaş,1699,NaN,2017-09-09,Şenol Güneş (since 2015-07-01),2017-09-12
23,24,61 Ολυμπιακός,1660,NaN,2017-09-09,Besnik Hasi (since 2017-07-01),2017-09-12
24,25,63 Спартак Москва,1659,NaN,2017-09-09,Massimo Carrera (since 2016-08-05),2017-09-12
25,26,66 Anderlecht,1656,NaN,2017-09-08,René Weiler (since 2016-07-01) René Peeters (s...,2017-09-12
26,27,88 Feyenoord,1626,NaN,2017-09-09,Giovanni van Bronckhorst (since 2015-05-18),2017-09-12
27,28,89 Basel,1621,NaN,2017-09-09,Raphaël Wicky (since 2017-07-01),2017-09-12
28,29,91 Celtic,1615,NaN,2017-09-08,Brendan Rodgers (since 2016-07-01),2017-09-12
29,30,94 ΑΠΟΕΛ,1611,NaN,2017-08-23,Georgios Donis (since 2017-07-29),2017-09-12
30,31,Qarabağ,1511,NaN,2017-08-23,Qurban Qurbanov (since 2008-07-01),2017-09-12
31,32,Maribor,1434,NaN,2017-09-08,Darko Milanič (since 2016-03-02),2017-09-12
32,1,1 Real Madrid,2067,NaN,2017-09-23,Zinédine Zidane (since 2016-01-05),2017-09-26
33,2,2 Barcelona,2051,NaN,2017-09-23,Ernesto Valverde (since 2017-07-01),2017-09-26
34,3,3 Bayern,1969,NaN,2017-09-22,Carlo Ancelotti (since 2016-07-01),2017-09-26
35,4,4 Atlético,1968,NaN,2017-09-23,Diego Simeone (since 2011-12-23),2017-09-26
36,5,5 Juventus,1962,NaN,2017-09-23,Massimiliano Allegri (since 2014-07-16),2017-09-26
37,6,6 Chelsea,1926,NaN,2017-09-23,Antonio Conte (since 2016-07-01),2017-09-26
38,7,7 Man City,1912,NaN,2017-09-23,Pep Guardiola (since 2016-07-01),2017-09-26
39,8,8 Paris SG,1901,NaN,2017-09-23,Unai Emery (since 2016-07-01),2017-09-26
40,9,9 Napoli,1900,NaN,2017-09-23,Maurizio Sarri (since 2015-06-11),2017-09-26
41,10,10 Tottenham,1899,NaN,2017-09-23,Mauricio Pochettino (since 2014-07-01),2017-09-26
42,11,11 Man United,1896,NaN,2017-09-23,José Mourinho (since 2016-07-01),2017-09-26
43,12,12 Monaco,1874,NaN,2017-09-22,Leonardo Jardim (since 2014-07-01),2017-09-26
44,13,13 Dortmund,1865,NaN,2017-09-23,Peter Bosz (since 2017-07-01),2017-09-26
45,14,15 Liverpool,1851,NaN,2017-09-23,Jürgen Klopp (since 2015-10-08),2017-09-26
46,15,16 Roma,1847,NaN,2017-09-23,Eusebio Di Francesco (since 2017-06-13),2017-09-26
47,16,17 Sevilla,1839,NaN,2017-09-23,Eduardo Berizzo (since 2017-07-01),2017-09-26
48,17,22 Шахтар,1771,NaN,2017-09-23,Paulo Fonseca (since 2016-07-01),2017-09-26
49,18,23 Benfica,1770,NaN,2017-09-23,Rui Vitória (since 2015-07-01),2017-09-26

In [11]:
# ############################################## 2018-19 ##############################################

# # 1. CSV-Datei mit CL-Spielen laden
# df = pd.read_csv("champions-league-2018-WEuropeStandardTime.csv")
# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
# df_sorted = df.sort_values(by="Date")

# # 2. Frühestes Spiel je Runde extrahieren (für URLs)
# first_dates_per_round = (
#     df_sorted.groupby("Round Number")["Date"]
#     .min()
#     .drop_duplicates()
#     .sort_values()
# )
# date_list_for_urls = first_dates_per_round.dt.strftime("%Y-%m-%d").tolist()

# # 3. Rankings von clubelo.com scrapen
# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
# ucl_rankings = {}

# for date in date_list_for_urls:
#     url = f"http://clubelo.com/{date}/UCL/Ranking"
#     print(f"Scraping: {url}")
    
#     try:
#         response = requests.get(url, headers=headers)
#         soup = BeautifulSoup(response.text, "html.parser")
#         table = soup.find("table", class_="ranking")
        
#         if table:
#             df_table = pd.read_html(str(table))[0]
#             df_table["Date"] = date
#             ucl_rankings[date] = df_table
#         else:
#             print(f"Tabelle nicht gefunden für {date}")
#             ucl_rankings[date] = None
#     except Exception as e:
#         print(f"Fehler bei {date}: {e}")
#         ucl_rankings[date] = None

#     time.sleep(5)

# # 4. Alle Tabellen zusammenfügen und speichern
# all_tables = [df for df in ucl_rankings.values() if df is not None]
# df_combined = pd.concat(all_tables, ignore_index=True)
# df_combined.to_csv("ucl_elo_rankings_2018_2019.csv", index=False)
# print("Fertig! Tabellen gespeichert in 'ucl_elo_rankings_2018_2019.csv'")

In [12]:
df_2018_19 = pd.read_csv("ucl_elo_rankings_2018_2019.csv")

In [13]:
df_2018_19

,Rank,Club,Elo,Unnamed: 3,Last Match,Coach,Date
0,1,1 Barcelona,2036,NaN,2018-09-15,Ernesto Valverde (since 2017-07-01),2018-09-18
1,2,2 Real Madrid,2024,NaN,2018-09-15,Julen Lopetegui (since 2018-07-01),2018-09-18
2,3,3 Man City,1977,NaN,2018-09-15,Pep Guardiola (since 2016-07-01),2018-09-18
3,4,4 Juventus,1966,NaN,2018-09-16,Massimiliano Allegri (since 2014-07-16),2018-09-18
4,5,5 Bayern,1960,NaN,2018-09-15,Niko Kovač (since 2018-07-01),2018-09-18
...,...,...,...,...,...,...,...
245,2,3 Liverpool,2003,NaN,2019-05-04,Jürgen Klopp (since 2015-10-08),2019-05-07
246,3,8 Tottenham,1877,NaN,2019-05-04,Mauricio Pochettino (since 2014-07-01),2019-05-07
247,4,13 Ajax,1836,NaN,2019-04-30,Erik ten Hag (since 2018-01-01),2019-05-07
248,1,1 Liverpool,2044,NaN,2019-05-12,Jürgen Klopp (since 2015-10-08),2019-06-01
249,2,5 Tottenham,1901,NaN,2019-05-12,Mauricio Pochettino (since 2014-07-01),2019-06-01

In [14]:
# ############################################## 2020-21 ##############################################

# # 1. CL-Spieldaten einlesen und nach Datum sortieren
# df = pd.read_csv("champions-league-2020-UTC.csv")
# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
# df_sorted = df.sort_values(by="Date")

# # 2. Frühestes Spiel je Runde als Grundlage für URL-Erstellung
# first_dates_per_round = (
#     df_sorted.groupby("Round Number")["Date"]
#     .min()
#     .drop_duplicates()
#     .sort_values()
# )
# date_list_for_urls = first_dates_per_round.dt.strftime("%Y-%m-%d").tolist()

# # 3. Elo-Rankings von clubelo.com scrapen
# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
# ucl_rankings = {}

# for date in date_list_for_urls:
#     url = f"http://clubelo.com/{date}/UCL/Ranking"
#     print(f"Scraping: {url}")
    
#     try:
#         response = requests.get(url, headers=headers)
#         soup = BeautifulSoup(response.text, "html.parser")
#         table = soup.find("table", class_="ranking")
        
#         if table:
#             df_table = pd.read_html(str(table))[0]
#             df_table["Date"] = date
#             ucl_rankings[date] = df_table
#         else:
#             print(f"Tabelle nicht gefunden für {date}")
#             ucl_rankings[date] = None
#     except Exception as e:
#         print(f"Fehler bei {date}: {e}")
#         ucl_rankings[date] = None
        
#     time.sleep(5)

# # 4. Tabellen kombinieren und als CSV speichern
# all_tables = [df for df in ucl_rankings.values() if df is not None]
# df_combined = pd.concat(all_tables, ignore_index=True)
# df_combined.to_csv("ucl_elo_rankings_2020_2021.csv", index=False)
# print("Fertig! Tabellen gespeichert in 'ucl_elo_rankings_2020_2021.csv'")

In [15]:
df_2020_21 = pd.read_csv("ucl_elo_rankings_2020_2021.csv")

In [16]:
df_2020_21

,Rank,Club,Elo,Unnamed: 3,Last Match,Coach,Date
0,1,1 Bayern,2025,NaN,2020-10-17,Hansi Flick (since 2019-11-03),2020-10-20
1,2,2 Liverpool,1966,NaN,2020-10-17,Jürgen Klopp (since 2015-10-08),2020-10-20
2,3,3 Barcelona,1953,NaN,2020-10-17,Ronald Koeman (since 2020-08-19),2020-10-20
3,4,4 Man City,1950,NaN,2020-10-17,Pep Guardiola (since 2016-07-01),2020-10-20
4,5,5 Paris SG,1916,NaN,2020-10-16,Thomas Tuchel (since 2018-07-01),2020-10-20
...,...,...,...,...,...,...,...
245,2,4 Real Madrid,1943,NaN,2021-05-01,Zinédine Zidane (since 2019-03-11),2021-05-04
246,3,7 Chelsea,1900,NaN,2021-05-01,Thomas Tuchel (since 2021-01-26),2021-05-04
247,4,10 Paris SG,1881,NaN,2021-05-01,Mauricio Pochettino (since 2021-01-02),2021-05-04
248,1,1 Man City,2024,NaN,2021-05-23,Pep Guardiola (since 2016-07-01),2021-05-29
249,2,7 Chelsea,1912,NaN,2021-05-23,Thomas Tuchel (since 2021-01-26),2021-05-29

In [17]:
# ############################################## 2021-22 ##############################################

# # 1. CL-Spieldaten einlesen und nach Datum sortieren
# df = pd.read_csv("champions-league-2021-UTC.csv")
# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
# df_sorted = df.sort_values(by="Date")

# # 2. Pro Runde das früheste Spieldatum extrahieren (für die URLs)
# first_dates_per_round = (
#     df_sorted.groupby("Round Number")["Date"]
#     .min()
#     .drop_duplicates()
#     .sort_values()
# )
# date_list_for_urls = first_dates_per_round.dt.strftime("%Y-%m-%d").tolist()

# # 3. Elo-Rankings zu den Spieltagen scrapen
# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
# ucl_rankings = {}

# for date in date_list_for_urls:
#     url = f"http://clubelo.com/{date}/UCL/Ranking"
#     print(f"Scraping: {url}")
    
#     try:
#         response = requests.get(url, headers=headers)
#         soup = BeautifulSoup(response.text, "html.parser")
#         table = soup.find("table", class_="ranking")
        
#         if table:
#             df_table = pd.read_html(str(table))[0]
#             df_table["Date"] = date
#             ucl_rankings[date] = df_table
#         else:
#             print(f"Tabelle nicht gefunden für {date}")
#             ucl_rankings[date] = None
#     except Exception as e:
#         print(f"Fehler bei {date}: {e}")
#         ucl_rankings[date] = None
        
#     time.sleep(5)

# # 4. Alle vorhandenen Rankings zusammenfügen und speichern
# all_tables = [df for df in ucl_rankings.values() if df is not None]
# df_combined = pd.concat(all_tables, ignore_index=True)
# df_combined.to_csv("ucl_elo_rankings_2021_2022.csv", index=False)
# print("Fertig! Tabellen gespeichert in 'ucl_elo_rankings_2021_2022.csv'")

In [18]:
df_2021_22 = pd.read_csv("ucl_elo_rankings_2021_2022.csv")

In [19]:
df_2021_22.head(6)

,Rank,Club,Elo,Unnamed: 3,Last Match,Coach,Date
0,1,1 Man City,2016,NaN,2021-09-11,Pep Guardiola (since 2016-07-01),2021-09-14
1,2,2 Bayern,2000,NaN,2021-09-11,Julian Nagelsmann (since 2021-07-01),2021-09-14
2,3,3 Liverpool,1955,NaN,2021-09-12,Jürgen Klopp (since 2015-10-08),2021-09-14
3,4,4 Real Madrid,1945,NaN,2021-09-12,Carlo Ancelotti (since 2021-07-01),2021-09-14
4,5,5 Chelsea,1944,NaN,2021-09-11,Thomas Tuchel (since 2021-01-26),2021-09-14
5,6,6 Man United,1937,NaN,2021-09-11,Ole Gunnar Solskjær (since 2018-12-19),2021-09-14

In [20]:
# ############################################## 2022-23 ##############################################

# # 1. CL-Spieldaten einlesen und nach Datum sortieren
# df = pd.read_csv("champions-league-2022-UTC.csv")
# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
# df_sorted = df.sort_values(by="Date")

# # 2. Pro Runde das früheste Spieldatum extrahieren (für die URLs)
# first_dates_per_round = (
#     df_sorted.groupby("Round Number")["Date"]
#     .min()
#     .drop_duplicates()
#     .sort_values()
# )
# date_list_for_urls = first_dates_per_round.dt.strftime("%Y-%m-%d").tolist()

# # 3. Elo-Rankings zu den Spieltagen scrapen
# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
# ucl_rankings = {}

# for date in date_list_for_urls:
#     url = f"http://clubelo.com/{date}/UCL/Ranking"
#     print(f"Scraping: {url}")
    
#     try:
#         response = requests.get(url, headers=headers)
#         soup = BeautifulSoup(response.text, "html.parser")
#         table = soup.find("table", class_="ranking")
        
#         if table:
#             df_table = pd.read_html(str(table))[0]
#             df_table["Date"] = date
#             ucl_rankings[date] = df_table
#         else:
#             print(f"Tabelle nicht gefunden für {date}")
#             ucl_rankings[date] = None
#     except Exception as e:
#         print(f"Fehler bei {date}: {e}")
#         ucl_rankings[date] = None
        
#     time.sleep(5)

# # 4. Alle vorhandenen Rankings zusammenfügen und speichern
# all_tables = [df for df in ucl_rankings.values() if df is not None]
# df_combined = pd.concat(all_tables, ignore_index=True)
# df_combined.to_csv("ucl_elo_rankings_2022_2023.csv", index=False)
# print("Fertig! Tabellen gespeichert in 'ucl_elo_rankings_2022_2023.csv'")

In [21]:
df_2022_23 = pd.read_csv("ucl_elo_rankings_2022_2023.csv")

In [22]:
df_2022_23

,Rank,Club,Elo,Unnamed: 3,Last Match,Coach,Date
0,1,1 Man City,2025,NaN,2022-09-03,Pep Guardiola (since 2016-07-01),2022-09-06
1,2,2 Liverpool,2007,NaN,2022-09-03,Jürgen Klopp (since 2015-10-08),2022-09-06
2,3,3 Real Madrid,1996,NaN,2022-09-03,Carlo Ancelotti (since 2021-07-01),2022-09-06
3,4,4 Bayern,1962,NaN,2022-09-03,Julian Nagelsmann (since 2021-07-01),2022-09-06
4,5,5 Barcelona,1898,NaN,2022-09-03,Xavi (since 2021-11-08),2022-09-06
...,...,...,...,...,...,...,...
245,2,4 Real Madrid,1926,NaN,2023-05-13,Carlo Ancelotti (since 2021-07-01),2023-05-16
246,3,8 Inter,1884,NaN,2023-05-13,Simone Inzaghi (since 2021-07-01),2023-05-16
247,4,17 Milan,1820,NaN,2023-05-13,Stefano Pioli (since 2019-10-09),2023-05-16
248,1,1 Man City,2072,NaN,2023-05-28,Pep Guardiola (since 2016-07-01),2023-06-10
249,2,7 Inter,1887,NaN,2023-06-03,Simone Inzaghi (since 2021-07-01),2023-06-10

In [23]:
# ############################################## 2023-24 ##############################################

# # 1. Spieldaten einlesen und nach Datum sortieren
# df = pd.read_csv("champions-league-2023-UTC.csv")
# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
# df_sorted = df.sort_values(by="Date")

# # 2. Früheste Spieltermine pro Runde als Datums-Liste für den Abruf vorbereiten
# first_dates_per_round = (
#     df_sorted.groupby("Round Number")["Date"]
#     .min()
#     .drop_duplicates()
#     .sort_values()
# )
# date_list_for_urls = first_dates_per_round.dt.strftime("%Y-%m-%d").tolist()

# # 3. Abruf der ClubElo-Rankings zu den Spieltagen
# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
# ucl_rankings = {}

# for date in date_list_for_urls:
#     url = f"http://clubelo.com/{date}/UCL/Ranking"
#     print(f"Scraping: {url}")
    
#     try:
#         response = requests.get(url, headers=headers)
#         soup = BeautifulSoup(response.text, "html.parser")
#         table = soup.find("table", class_="ranking")
        
#         if table:
#             df_table = pd.read_html(str(table))[0]
#             df_table["Date"] = date
#             ucl_rankings[date] = df_table
#         else:
#             print(f"Tabelle nicht gefunden für {date}")
#             ucl_rankings[date] = None
#     except Exception as e:
#         print(f"Fehler bei {date}: {e}")
#         ucl_rankings[date] = None
        
#     time.sleep(5)

# # 4. Tabellen zusammenfügen und lokal speichern
# all_tables = [df for df in ucl_rankings.values() if df is not None]
# df_combined = pd.concat(all_tables, ignore_index=True)
# df_combined.to_csv("ucl_elo_rankings_2023_2024.csv", index=False)
# print("Fertig! Tabellen gespeichert in 'ucl_elo_rankings_2023_2024.csv'")

In [24]:
df_2023_24 = pd.read_csv("ucl_elo_rankings_2023_2024.csv")

In [25]:
df_2023_24.head(5)

,Rank,Club,Elo,Unnamed: 3,Last Match,Coach,Date
0,1,1 Man City,2091,NaN,2023-09-16,Pep Guardiola (since 2016-07-01),2023-09-19
1,2,3 Bayern,1940,NaN,2023-09-15,Thomas Tuchel (since 2023-03-24),2023-09-19
2,3,4 Arsenal,1932,NaN,2023-09-17,Mikel Arteta (since 2019-12-22),2023-09-19
3,4,5 Real Madrid,1922,NaN,2023-09-17,Carlo Ancelotti (since 2021-07-01),2023-09-19
4,5,6 Inter,1909,NaN,2023-09-16,Simone Inzaghi (since 2021-07-01),2023-09-19

In [26]:
# Einlesen des vorbereiteten kombinierten Champions-League-Datensatzes (aus Excel-Datei)
combined_df = pd.read_excel(r"C:\Users\charb\Downloads\combined_df_full.xlsx")

In [27]:
combined_df

,Match Number,Round Number,Date,Location,Home Team,Away Team,Group,Result,Home Goals,Away Goals,Elo Home,Elo Away
0,1,1,2017-09-12 20:45:00,"Estádio da Luz, Lisbon",Benfica,CSKA Moscow,Group A,1 - 2,1,2,1797.0,1723.0
1,2,1,2017-09-12 20:45:00,"Old Trafford, Manchester",Manchester United,Basel,Group A,3 - 0,3,0,NaN,1621.0
2,13,1,2017-09-12 20:45:00,"Allianz Arena, Munich",Bayern Munich,Anderlecht,Group B,3 - 0,3,0,NaN,1656.0
3,14,1,2017-09-12 20:45:00,"Celtic Park, Glasgow",Celtic,Paris Saint-Germain,Group B,0 - 5,0,5,1615.0,NaN
4,25,1,2017-09-12 20:45:00,"Stamford Bridge, London",Chelsea,Qarabag,Group C,6 - 0,6,0,1919.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
745,121,SF Game 1,2024-04-30 19:00:00,Fußball Arena München,Bayern Munich,Real Madrid,NaN,2 - 2,2,2,1941.0,1984.0
746,122,SF Game 1,2024-05-01 19:00:00,BVB Stadion Dortmund,Borussia Dortmund,Paris Saint-Germain,NaN,1 - 0,1,0,1880.0,NaN
747,123,SF Game 2,2024-05-07 19:00:00,Parc des Princes,Paris Saint-Germain,Borussia Dortmund,NaN,0 - 1,0,1,NaN,1890.0
748,124,SF Game 2,2024-05-08 19:00:00,Estadio Santiago Bernabéu,Real Madrid,Bayern Munich,NaN,2 - 1,2,1,1988.0,1927.0
749,125,Final,2024-06-01 19:00:00,Wembley Stadium,Borussia Dortmund,Real Madrid,NaN,0 - 2,0,2,1879.0,1988.0

In [28]:
# Laden der zusammengeführten historischen Elo-Ratings für alle Champions-League-Saisons (2017–2024)
# Diese Datei wurde zuvor aus den ClubElo-Webseiten gescraped und in Excel gespeichert
elo_data_merged = pd.read_excel(r"C:\Users\charb\Downloads\elo_data_merged_2017_2024.xlsx")

In [29]:
elo_data_merged

,Rank,Club,Elo,Unnamed: 3,Last Match,Coach,Date,Clean Club
0,1,1 Real Madrid,2072,NaN,2017-09-09,Zinédine Zidane (since 2016-01-05),2017-09-12,real madrid
1,2,2 Barcelona,2033,NaN,2017-09-09,Ernesto Valverde (since 2017-07-01),2017-09-12,barcelona
2,3,3 Bayern Munich,1974,NaN,2017-09-09,Carlo Ancelotti (since 2016-07-01),2017-09-12,Bayern Munich
3,4,4 Juventus,1954,NaN,2017-09-09,Massimiliano Allegri (since 2014-07-16),2017-09-12,juventus
4,5,5 Atlético Madrid,1951,NaN,2017-09-09,Diego Simeone (since 2011-12-23),2017-09-12,Atlético Madrid
...,...,...,...,...,...,...,...,...
1495,2,6 Bayern Munich,1927,NaN,2024-05-04,Thomas Tuchel (since 2023-03-24),2024-05-07,Bayern Munich
1496,3,7 Paris Saint-Germain,1910,NaN,2024-05-01,Luis Enrique (since 2023-07-05),2024-05-07,Paris Saint-Germain
1497,4,9 Borussia Dortmund,1890,NaN,2024-05-04,Edin Terzić (since 2022-05-24),2024-05-07,Borussia Dortmund
1498,1,2 Real Madrid,1988,NaN,2024-05-25,Carlo Ancelotti (since 2021-07-01),2024-06-01,real madrid
1499,2,10 Borussia Dortmund,1879,NaN,2024-05-18,Edin Terzić (since 2022-05-24),2024-06-01,Borussia Dortmund

In [30]:
# Datumsspalten in beide DataFrames konvertieren (für zeitbasiertes Matching)
elo_data_merged["Date"] = pd.to_datetime(elo_data_merged["Date"])
combined_df["Date"] = pd.to_datetime(combined_df["Date"], dayfirst=True)

# Clubnamen bereinigen (z. B. '1 Man City' → 'man city') für einheitlichen Abgleich
def clean_club_name(name):
    name = str(name)
    name = re.sub(r"^\d+\s+", "", name)
    return name.strip().lower()

# Neue Spalte 'Clean Club' im Elo-Datensatz zur Vereinfachung des Abgleichs
elo_data_merged["Clean Club"] = elo_data_merged["Club"].apply(clean_club_name)

# Zwei neue Spalten zur Speicherung der passenden Elo-Werte im Spiel-Datensatz
combined_df["Elo Home"] = None
combined_df["Elo Away"] = None

# Hauptschleife: Für jedes Spiel das passende Elo-Rating der Teams ermitteln
for idx, row in combined_df.iterrows():
    match_date = row["Date"]
    home_team = clean_club_name(row["Home Team"])
    away_team = clean_club_name(row["Away Team"])

    # Letztes verfügbares Elo-Datum vor oder am Spieltag
    elo_date = elo_data_merged[elo_data_merged["Date"] <= match_date]["Date"].max()

    if pd.isna(elo_date):
        continue

    snapshot = elo_data_merged[elo_data_merged["Date"] == elo_date]

    # Elo-Rating für Heimteam zuweisen
    home_row = snapshot[snapshot["Clean Club"] == home_team]
    if not home_row.empty:
        combined_df.at[idx, "Elo Home"] = home_row.iloc[0]["Elo"]

    # Elo-Rating für Auswärtsteam zuweisen
    away_row = snapshot[snapshot["Clean Club"] == away_team]
    if not away_row.empty:
        combined_df.at[idx, "Elo Away"] = away_row.iloc[0]["Elo"]

In [31]:
# Ergebnis anzeigen
combined_df.head(50)

,Match Number,Round Number,Date,Location,Home Team,Away Team,Group,Result,Home Goals,Away Goals,Elo Home,Elo Away
0,1,1,2017-09-12 20:45:00,"Estádio da Luz, Lisbon",Benfica,CSKA Moscow,Group A,1 - 2,1,2,1797,1723
1,2,1,2017-09-12 20:45:00,"Old Trafford, Manchester",Manchester United,Basel,Group A,3 - 0,3,0,1879,1621
2,13,1,2017-09-12 20:45:00,"Allianz Arena, Munich",Bayern Munich,Anderlecht,Group B,3 - 0,3,0,1974,1656
3,14,1,2017-09-12 20:45:00,"Celtic Park, Glasgow",Celtic,Paris Saint-Germain,Group B,0 - 5,0,5,1615,1889
4,25,1,2017-09-12 20:45:00,"Stamford Bridge, London",Chelsea,Qarabag,Group C,6 - 0,6,0,1919,1511
5,26,1,2017-09-12 20:45:00,"Stadio Olimpico, Rome",Roma,Atlético Madrid,Group C,0 - 0,0,0,1832,1951
6,37,1,2017-09-12 20:45:00,"Camp Nou, Barcelona",Barcelona,Juventus,Group D,3 - 0,3,0,2033,1954
7,38,1,2017-09-12 20:45:00,"Karaiskakis Stadium, Piraeus",Olympiacos,Sporting CP,Group D,2 - 3,2,3,1660,1720
8,49,1,2017-09-13 20:45:00,"Ljudski vrt, Maribor",Maribor,Spartak Moscow,Group E,1 - 1,1,1,1434,1659
9,50,1,2017-09-13 20:45:00,"Anfield, Liverpool",Liverpool,Sevilla,Group E,2 - 2,2,2,1852,1829
10,61,1,2017-09-13 20:45:00,"De Kuip, Rotterdam",Feyenoord,Manchester City,Group F,0 - 4,0,4,1626,1889
11,62,1,2017-09-13 20:45:00,"Metalist Stadium, Kharkiv",Shakhtar Donetsk,Napoli,Group F,2 - 1,2,1,1773,1889
12,73,1,2017-09-13 20:45:00,"Red Bull Arena, Leipzig",RB Leipzig,Monaco,Group G,1 - 1,1,1,1721,1860
13,74,1,2017-09-13 20:45:00,"Estádio do Dragão, Porto",Porto,Besiktas,Group G,1 - 3,1,3,1754,1699
14,85,1,2017-09-13 20:45:00,"Santiago Bernabéu, Madrid",Real Madrid,APOEL,Group H,3 - 0,3,0,2072,1611
15,86,1,2017-09-13 20:45:00,"Wembley Stadium, London",Tottenham Hotspur,Borussia Dortmund,Group H,3 - 1,3,1,1893,1859
16,51,2,2017-09-26 20:45:00,"Ramón Sánchez Pizjuán, Seville",Sevilla,Maribor,Group E,3 - 0,3,0,1839,1452
17,52,2,2017-09-26 20:45:00,"Otkrytiye Arena, Moscow",Spartak Moscow,Liverpool,Group E,1 - 1,1,1,1652,1851
18,63,2,2017-09-26 20:45:00,"Stadio San Paolo, Naples",Napoli,Feyenoord,Group F,3 - 1,3,1,1900,1584
19,64,2,2017-09-26 20:45:00,"City of Manchester Stadium, Manchester",Manchester City,Shakhtar Donetsk,Group F,2 - 0,2,0,1912,1771
20,75,2,2017-09-26 20:45:00,"Vodafone Park, Istanbul",Besiktas,RB Leipzig,Group G,2 - 0,2,0,1713,1710
21,76,2,2017-09-26 20:45:00,"Stade Louis II, Monaco",Monaco,Porto,Group G,0 - 3,0,3,1874,1742
22,87,2,2017-09-26 20:45:00,"Westfalenstadion, Dortmund",Borussia Dortmund,Real Madrid,Group H,1 - 3,1,3,1865,2067
23,88,2,2017-09-26 20:45:00,"GSP Stadium, Nicosia",APOEL,Tottenham Hotspur,Group H,0 - 3,0,3,1612,1899
24,27,2,2017-09-27 18:00:00,"Tofiq Bahramov Republican Stadium, Baku",Qarabag,Roma,Group C,1 - 2,1,2,1508,1847
25,3,2,2017-09-27 20:45:00,"St. Jakob-Park, Basel",Basel,Benfica,Group A,5 - 0,5,0,1605,1770
26,4,2,2017-09-27 20:45:00,"VEB Arena, Moscow",CSKA Moscow,Manchester United,Group A,1 - 4,1,4,1744,1896
27,15,2,2017-09-27 20:45:00,"Parc des Princes, Paris",Paris Saint-Germain,Bayern Munich,Group B,3 - 0,3,0,1901,1969
28,16,2,2017-09-27 20:45:00,"Constant Vanden Stock Stadium, Anderlecht",Anderlecht,Celtic,Group B,0 - 3,0,3,1648,1606
29,28,2,2017-09-27 20:45:00,"Wanda Metropolitano, Madrid",Atlético Madrid,Chelsea,Group C,1 - 2,1,2,1968,1926
30,39,2,2017-09-27 20:45:00,"Estádio José Alvalade, Lisbon",Sporting CP,Barcelona,Group D,0 - 1,0,1,1724,2051
31,40,2,2017-09-27 20:45:00,"Juventus Stadium, Turin",Juventus,Olympiacos,Group D,2 - 0,2,0,1962,1636
32,53,3,2017-10-17 20:45:00,"Otkrytiye Arena, Moscow",Spartak Moscow,Sevilla,Group E,5 - 1,5,1,1669,1828
33,54,3,2017-10-17 20:45:00,"Ljudski vrt, Maribor",Maribor,Liverpool,Group E,0 - 7,0,7,1446,1853
34,65,3,2017-10-17 20:45:00,"City of Manchester Stadium, Manchester",Manchester City,Napoli,Group F,2 - 1,2,1,1938,1916
35,66,3,2017-10-17 20:45:00,"De Kuip, Rotterdam",Feyenoord,Shakhtar Donetsk,Group F,1 - 2,1,2,1588,1778
36,77,3,2017-10-17 20:45:00,"Stade Louis II, Monaco",Monaco,Besiktas,Group G,1 - 2,1,2,1827,1704
37,78,3,2017-10-17 20:45:00,"Red Bull Arena, Leipzig",RB Leipzig,Porto,Group G,3 - 2,3,2,1702,1764
38,89,3,2017-10-17 20:45:00,"GSP Stadium, Nicosia",APOEL,Borussia Dortmund,Group H,1 - 1,1,1,1606,1829
39,90,3,2017-10-17 20:45:00,"Santiago Bernabéu, Madrid",Real Madrid,Tottenham Hotspur,Group H,1 - 1,1,1,2069,1920
40,29,3,2017-10-18 18:00:00,"Tofiq Bahramov Republican Stadium, Baku",Qarabag,Atlético Madrid,Group C,0 - 0,0,0,1504,1943
41,5,3,2017-10-18 20:45:00,"VEB Arena, Moscow",CSKA Moscow,Basel,Group A,0 - 2,0,2,1735,1635
42,6,3,2017-10-18 20:45:00,"Estádio da Luz, Lisbon",Benfica,Manchester United,Group A,0 - 1,0,1,1741,1919
43,17,3,2017-10-18 20:45:00,"Constant Vanden Stock Stadium, Anderlecht",Anderlecht,Paris Saint-Germain,Group B,0 - 4,0,4,1627,1913
44,18,3,2017-10-18 20:45:00,"Allianz Arena, Munich",Bayern Munich,Celtic,Group B,3 - 0,3,0,1932,1629
45,30,3,2017-10-18 20:45:00,"Stamford Bridge, London",Chelsea,Roma,Group C,3 - 3,3,3,1922,1855
46,41,3,2017-10-18 20:45:00,"Juventus Stadium, Turin",Juventus,Sporting CP,Group D,2 - 1,2,1,1949,1719
47,42,3,2017-10-18 20:45:00,"Camp Nou, Barcelona",Barcelona,Olympiacos,Group D,3 - 1,3,1,2046,1623
48,7,4,2017-10-31 20:45:00,"St. Jakob-Park, Basel",Basel,CSKA Moscow,Group A,1 - 2,1,2,1667,1703
49,8,4,2017-10-31 20:45:00,"Old Trafford, Manchester",Manchester United,Benfica,Group A,2 - 0,2,0,1920,1727

In [32]:
# Zeige alle Spiele, bei denen der Elo-Wert für Heim- oder Auswärtsteam fehlt
missing_elos = combined_df[
    combined_df["Elo Home"].isna() | combined_df["Elo Away"].isna()
]

# Anzahl dieser Zeilen anzeigen
print(f"Es gibt {missing_elos.shape[0]} Zeilen mit fehlenden Elo-Werten")

Es gibt 0 Zeilen mit fehlenden Elo-Werten

In [33]:
# Zeilenweise Verarbeitung
expanded_rows = []

for idx, row in combined_df.iterrows():
    if pd.isna(row["Elo Home"]) or pd.isna(row["Elo Away"]):
        continue  # Spiele ohne vollständige Elo-Werte überspringen

    # Elo-Differenzen aus Sicht beider Teams
    elo_diff_home = row["Elo Home"] - row["Elo Away"]
    elo_diff_away = row["Elo Away"] - row["Elo Home"]

    # Heimvorteil nur setzen, wenn kein Finale
    is_final = str(row["Round Number"]).strip().lower() == "final"
    home_dummy = 0 if is_final else 1
    away_dummy = 0  # Auswärtsteam hat nie Heimvorteil

    # Heimteam-Zeile hinzufügen
    expanded_rows.append({
        "Date": row["Date"],
        "Team": row["Home Team"],
        "Goals": row["Home Goals"],
        "Elo_Diff": elo_diff_home,
        "Home": home_dummy
    })

    # Auswärtsteam-Zeile hinzufügen
    expanded_rows.append({
        "Date": row["Date"],
        "Team": row["Away Team"],
        "Goals": row["Away Goals"],
        "Elo_Diff": elo_diff_away,
        "Home": away_dummy
    })

# In DataFrame umwandeln
model_df = pd.DataFrame(expanded_rows)

# Vorschau der neuen Struktur
model_df.head()

                 Date               Team  Goals  Elo_Diff  Home
0 2017-09-12 20:45:00            Benfica      1        74     1
1 2017-09-12 20:45:00        CSKA Moscow      2       -74     0
2 2017-09-12 20:45:00  Manchester United      3       258     1
3 2017-09-12 20:45:00              Basel      0      -258     0
4 2017-09-12 20:45:00      Bayern Munich      3       318     1

In [34]:
model_df.to_excel("model_df.xlsx", index=False)